---
title: ""
output: pdf_document
---

```{r, setup, include=FALSE}
knitr::opts_chunk$set(
  cache = TRUE, out.width = "100%", align = 'center', fig.width = 7, fig.height = 7
)
```

```{r install-data-package, include = FALSE}
# Run only once if needed to install data package 
if (!require("foodbanksHamilton", character.only = TRUE)) {
  devtools::install_github("https://github.com/paezha/Accessibility-Food-Banks-Hamilton", subdir = "foodbanksHamilton")
}
```

```{r load-packages, cache=FALSE, include=FALSE}
library(foodbanksHamilton) # Data package
library(kableExtra)
library(patchwork)
library(sf)
library(spdep)
library(tidyverse)
```

```{r directory-for-figures, include=FALSE}
ifelse(!dir.exists(file.path("./figures")), dir.create(file.path("./figures")), FALSE)
```

```{r invoke-data, include=FALSE}
data(data_da_2016)
data(dwelling_network_points_2016)
data(foodbank_locations)
data(foodbank_table)
data(hamilton_boundary)
data(modes_less40k)
data(population_age_income)
data(ttm_car)
data(ttm_transit)
data(ttm_walk)

# load updated files manually
#load("./output-data-files/ttm_transit.RData")
#load("./output-data-files/foodbank_table.RData")
```

```{r remove-irrelevant-destinations, include=FALSE}
## Data preparation
# Remove entries in travel time matrices for inapplicable destinations
# As a first step, we will remove the computed travel times to the three Community Kitchen locations (IDs 1-3):
ttm_car <- ttm_car %>%
  filter(!between(OBJECTID, left = 1, right = 3))

ttm_transit <- ttm_transit %>%
  filter(!between(OBJECTID, left = 1, right = 3))

ttm_walk <- ttm_walk %>%
  filter(!between(OBJECTID, left = 1, right = 3))
```

```{r join-low-income-households, include=FALSE}
## Data preparation
# Join proportion of low income households per DA to dwellings and total number of residential units:
dwelling_network_points_2016 <- dwelling_network_points_2016 %>%
  left_join(data_da_2016 %>%
              st_drop_geometry() %>%
              dplyr::transmute(DAUID = GeoUID, 
                               p_inc_less40k),
            by = "DAUID")
```

```{r probability-of-low-income-per-parcel, include=FALSE}
## Data preparation
# Calculate probability that a point on the network will have low income households. This is the proportion of low income households in the DA multiplied by the total number of residential units at the point:
dwelling_network_points_2016 <- dwelling_network_points_2016 %>%
  mutate(income_less40k = p_inc_less40k * Dwellings)
```

```{r number-of-residential-units-per-DA, include=FALSE}
## Data preparation
# Prepare and join population data from Transportation Tomorrow Survey
# Find number of residential units in each DA. This is needed to assign the population to parcels
residential_units <- dwelling_network_points_2016 %>%
  st_drop_geometry() %>%
  group_by(TAZUID) %>%
  summarize(residential_units = sum(Dwellings))
```

```{r join-population-to-parcels, include=FALSE}
## Data preparation
# Join number of low income households per DA to dwellings and total number of residential units:
dwelling_network_points_2016 <- dwelling_network_points_2016 %>%
  left_join(population_age_income %>%
              st_drop_geometry() %>%
              dplyr::transmute(TAZUID,
                               children,
                               adults,
                               seniors),
            by = "TAZUID") %>%
  left_join(residential_units,
            by = "TAZUID")
```

```{r calculate-low-income-households-per-parcel, include=FALSE}
## Data preparation
# Calculate population per point on the network. This is the population in the DA divided by the total number of residential units. This gives the average number of people per residential unit. Then, multiply by the number of dwellings (residential units) at the point:
dwelling_network_points_2016 <- dwelling_network_points_2016 %>%
  mutate(children = (children/residential_units) * Dwellings,
         adults = (adults/residential_units) * Dwellings,
         seniors = (seniors/residential_units) * Dwellings)
```

```{r join-household-data-to-travel-time-tables, include=FALSE}
## Data preparation
# Join the household data to the travel time matrices:
ttm_car <- ttm_car %>%
  left_join(dwelling_network_points_2016 %>%
              st_drop_geometry() %>%
              dplyr::select(ID, 
                            income_less40k,
                            children,
                            adults,
                            seniors,
                            DAUID, 
                            TAZUID),
            by = c("UID" = "ID"))

ttm_transit <- ttm_transit %>%
  left_join(dwelling_network_points_2016 %>%
              st_drop_geometry() %>%
              dplyr::select(ID, 
                            income_less40k,
                            children,
                            adults,
                            seniors,
                            DAUID, 
                            TAZUID),
            by = c("UID" = "ID"))

ttm_walk <- ttm_walk %>%
  left_join(dwelling_network_points_2016 %>%
              st_drop_geometry() %>%
              dplyr::select(ID, 
                            income_less40k,
                            children,
                            adults,
                            seniors,
                            DAUID, 
                            TAZUID),
            by = c("UID" = "ID"))
```

```{r join-foodbank-data-to-travel-time-tables, include=FALSE}
## Data preparation
# Join the foodbank data to the travel time tables:
ttm_car <- ttm_car %>%
  left_join(foodbank_locations %>%
              st_drop_geometry() %>%
              dplyr::select(ID, 
                            TYPE,
                            COVIDClose),
            by = c("OBJECTID" = "ID"))

ttm_transit <- ttm_transit %>%
  left_join(foodbank_locations %>%
              st_drop_geometry() %>%
              dplyr::select(ID, 
                            TYPE,
                            COVIDClose),
            by = c("OBJECTID" = "ID"))

ttm_walk <- ttm_walk %>%
  left_join(foodbank_locations %>%
              st_drop_geometry() %>%
              dplyr::select(ID,
                            TYPE,
                            COVIDClose),
            by = c("OBJECTID" = "ID"))
```

```{r drop-nas-from-travel-time-tables, include=FALSE}
## Data preparation
# Drop NAs:
ttm_car <- ttm_car %>%
  drop_na(TAZUID,
          income_less40k)

ttm_transit <- ttm_transit %>%
  drop_na(TAZUID,
          income_less40k)

ttm_walk <- ttm_walk %>%
  drop_na(TAZUID,
          income_less40k)
```

```{r proportion-of-trips-by-mode-by-taz, include=FALSE}
## Data preparation
# Calculate proportion of trips by mode per TAZ:
modes <- modes_less40k %>%
  mutate(p_car = Driver/(Driver + Transit + Walk),
         p_transit = Transit/(Driver + Transit + Walk),
         p_walk = Walk/(Driver + Transit + Walk))
```

```{r fill-nas-transport-modes, include=FALSE}
## Data preparation
# Assume that TAZ with NAs have a proportion of car trips of one:
modes <- modes %>%
  dplyr::mutate(p_car = replace_na(p_car, 1),
                p_transit = replace_na(p_transit, 0),
                p_walk = replace_na(p_walk, 0))
```

```{r join-trips-by-mode-to-travel-time-tables, include=FALSE}
## Data preparation
# Join trip-making modal proportions
ttm_car <- ttm_car %>%
  left_join(modes %>%
              st_drop_geometry() %>%
              transmute(TAZUID,
                        p_car,
                        p_transit,
                        p_walk),
            by = "TAZUID")

ttm_transit <- ttm_transit %>%
  left_join(modes %>%
              st_drop_geometry() %>%
              transmute(TAZUID,
                        p_car,
                        p_transit,
                        p_walk),
            by = "TAZUID")

ttm_walk <- ttm_walk %>%
  left_join(modes %>%
              st_drop_geometry() %>%
              transmute(TAZUID,
                        p_car,
                        p_transit,
                        p_walk),
            by = "TAZUID")
```

```{r join-travel-time-tables, include=FALSE}
## Data preparation
# Join Tables into Single TTM
ttm <- ttm_car %>%
  rename(travel_time_car = travel_time) %>%
  full_join(ttm_transit %>%
              transmute(UID,
                        OBJECTID,
                        travel_time_transit = travel_time),
            by = c("UID", "OBJECTID")) %>%
  full_join(ttm_walk %>%
              transmute(UID,
                        OBJECTID,
                        travel_time_walk = travel_time),
            by = c("UID", "OBJECTID"))
```

```{r travel-time-tables-data-check, include=FALSE}
## Data preparation - 2020
# Check the NAs in travel time table:
ttm %>% 
  filter(is.na(travel_time_transit)) %>%
  select(travel_time_transit,
         p_transit) %>%
  summary()

# What do NAs here mean? Most DAs missing travel time by transit do not report trips by transit in the TTS. In some DAs there are trips by transit (p_transit != 0), but no foodbank can be reached by transit (travel_time_transit is NA). How many of these cases?
ttm %>% 
  filter(is.na(travel_time_transit) & p_transit > 0) %>%
  select(travel_time_transit,
         p_transit) %>%
  summary()

# It should be fine to replace the NAs with zeros, which multiplied by p_transit will return a zero (i.e., it is not possible to reach a foodbank by transit).
#ttm_2021 <- ttm_2021 %>% 
#  mutate(travel_time_transit = replace_na(travel_time_transit, 0))

# Check the NAs in travel time by walk:
ttm %>% 
  filter(is.na(travel_time_walk)) %>%
  select(travel_time_walk,
         p_walk) %>%
  summary()

# Most DAs missing travel time by walking do not report trips by walking in the TTS. In some DAs there are trips by walking (p_walk != 0), but no foodbank can be reached by walk (travel_time_walk is NA). How many of these cases?
ttm %>% 
  filter(is.na(travel_time_walk) & p_walk > 0) %>%
  select(travel_time_walk,
         p_walk) %>%
  summary()

# Like with transit, it should be fine to replace the NAs with zeros, which multiplied by p_walk will return a zero (i.e., it is not possible to reach a foodbank by walking).
#ttm_2021 <- ttm_2021 %>% 
#  mutate(travel_time_walk = replace_na(travel_time_walk, 0))

#Summary of the table after these operations:
summary(ttm)
```

```{r calculate-expected-travel-times-old, eval = FALSE, include=FALSE}
## Data preparation
# Calculate expected travel times by mode. These are the travel time by the mode multiplied by the probability of using the mode (which is proxied by the proportion of trips by mode in the DA from the TTS). The total expected travel time is the sum of the expected travel times by mode:
#ttm_2021 <- ttm_2021 %>%
#  mutate(e_travel_time_car = travel_time_car * p_car,
#         e_travel_time_transit = travel_time_transit * p_transit,
#         e_travel_time_walk = travel_time_walk * p_walk,
#         e_travel_time = e_travel_time_car + e_travel_time_transit + e_travel_time_walk)
```

```{r calculate-expected-travel-times, include=FALSE}
ttm_long <- ttm %>% transmute(UID, OBJECTID,
                                        car_prob = p_car, 
                                        transit_prob = p_transit, 
                                        walk_prob = p_walk, 
                                        car_traveltime = travel_time_car, 
                                        transit_traveltime = travel_time_transit, 
                                        walk_traveltime = travel_time_walk) %>% 
  pivot_longer(cols = !c("UID", "OBJECTID"), 
               names_to = c("mode", ".value"),
               names_sep = "_") %>%
  group_by(UID, OBJECTID) %>%
  summarize(e_travel_time = weighted.mean(traveltime, prob, na.rm = TRUE))
# income_less40k = first(income_less40k)) %>% 
#  filter(!is.nan(e_travel_time))

ttm <- ttm %>% left_join(ttm_long, by = c("UID", "OBJECTID")) %>% 
  filter(!is.nan(e_travel_time))
```

```{r table-food-bank-info, echo=FALSE, results='asis'}
foodbank_table %>% kable("latex",
                         booktabs = TRUE,
                         align = ("cccccc"),
                         col.names = c("Type", 
                                       "Description", 
                                       "Locations Pre-COVID", 
                                       "Locations During COVID", 
                                       "Additional Notes"),
                         caption = "\\label{tab:food-bank-info}foodbank and Food Service Information.",
                         escape = FALSE) %>%
  kable_styling(latex_options = c("striped", "scale_down")) %>%
  column_spec(2, width = "15em") %>%
  column_spec(5, width = "15em")
```

```{r results-pre-covid, include=FALSE}
## Analysis 
# Calculate k-min accessibility pre-covid:
results_pre <- ttm %>%
  #dplyr::filter(COVIDClose == "No") %>%
  transmute(UID, 
            OBJECTID, 
            travel_time = e_travel_time, 
            population = income_less40k, 
            supply = 1) %>%
  b2sfca(threshold = 15)
```

```{r results-during-covid, include=FALSE}
## Analysis 
# Calculate k-min accessibility during covid:
results_covid <- ttm %>%
  dplyr::filter(COVIDClose == "No") %>%
  transmute(UID, 
            OBJECTID, 
            travel_time = e_travel_time, 
            population = income_less40k, 
            supply = 1) %>%
  b2sfca(threshold = 15)
```

```{r, bind-accessibility-results, include=FALSE}
## Analysis
# Bind level of service results:
los <- rbind(data.frame(results_pre$los, 
                        timing = "Pre-covid", 
                        threshold = "30 min"),
             data.frame(results_covid$los, 
                        timing = "During covid", 
                        threshold = "30 min")) %>%
  mutate(timing = factor(timing, 
                         levels = c("Pre-covid", 
                                    "During covid"),
                         ordered = TRUE))

# Bind accessibility results:
accessibility <- rbind(data.frame(results_pre$accessibility, 
                                  timing = "Pre-covid", 
                                  threshold = "30 min"),
                       data.frame(results_covid$accessibility, 
                                  timing = "During covid", 
                                  threshold = "30 min")) %>%
  mutate(timing = factor(timing, 
                         levels = c("Pre-covid", 
                                    "During covid"),
                         ordered = TRUE))
```

```{r join-zonal-ids-to-accessibility-table, include=FALSE}
## Analysis
# Join zonal identifiers to accessibility results:
accessibility <- accessibility %>%
  left_join(dwelling_network_points_2016 %>%
              st_drop_geometry() %>%
              dplyr::select(ID,
                            DAUID,
                            TAZUID,
                            children,
                            adults,
                            seniors),
            by = c("UID" = "ID")) %>%
  left_join(population_age_income %>%
              st_drop_geometry() %>%
              transmute(TAZUID),
            by = "TAZUID") 
```

```{r, join-geometry-to-level-of-service, include=FALSE}
## Analysis 
# Join geometry:
los <- los %>%
  left_join(foodbank_locations %>%
              dplyr::select(ID),
            by = c("OBJECTID" = "ID")) %>%
  st_as_sf()
```

```{r aggregate-accessibility-by-taz, include=FALSE}
## Analysis
# Accessibility by TAZ:
accessibility_taz <- accessibility %>%
  group_by(TAZUID, 
           timing) %>%
  summarize(accessibility = sum(accessibility),
            timing = first(timing),
            .groups = "drop") %>%
  left_join(population_age_income %>%
              transmute(TAZUID,
                        children,
                        adults,
                        seniors),
            by = "TAZUID") %>%
  st_as_sf()
```

```{r accessibility-changes-by-taz, include=FALSE}
## Analysis
# Calculate accessibility change by TAZ:
accessibility_taz_change <- accessibility_taz %>%
  st_drop_geometry() %>%
  pivot_wider(names_from = timing, 
              values_from = accessibility) %>%
  # Calculate changes in accessibility
  mutate(acc_d = `During covid` - `Pre-covid`) %>%
  # Join TAZ geometry
  left_join(population_age_income %>%
              transmute(TAZUID,
                        geometry),
            by = "TAZUID") %>%
  # Convert to simple features
  st_as_sf()
```

```{r accessibility-change-by-parcel, include=FALSE}
## Analysis
# Calculate accessibility change by parcel:
accessibility_change <- accessibility %>%
  select(UID, timing, accessibility) %>%
  pivot_wider(names_from = timing, 
              values_from = accessibility,
              values_fill = 0) %>%
  # Calculate changes in accessibility
  mutate(acc_d = `During covid` - `Pre-covid`)
```

```{r join-accessibility-change-to-table, include=FALSE}
## Analysis
# Join accessibility change to accessibility table:
accessibility <- accessibility %>%
  left_join(accessibility_change %>%
              select(UID, acc_d),
            by = "UID")
```

```{r quartiles-of-accessibility-change, include=FALSE}
## Analysis
# Quantiles of accessibility pre-covid:
acc_quantiles_pre <- quantile(accessibility_change$`Pre-covid`,
                              c(0, 0.25, 0.5, 0.75, 1))
# Quantiles of accessibility change:
acc_quantiles_during <- quantile(accessibility_change$`During covid`,
                                 c(0, 0.25, 0.5, 0.75, 1))
```

```{r accessibility-labels, include=FALSE}
## Analysis
# Add labels of accessibility loss to table:
accessibility <- accessibility %>%
  mutate(accessibility_pre_level = case_when(accessibility <= acc_quantiles_pre[2] ~ "Bottom 25\\%",
                                             accessibility > acc_quantiles_pre[2] & accessibility <= acc_quantiles_pre[3] ~ "Third 25\\%",
                                             accessibility > acc_quantiles_pre[3] & accessibility <= acc_quantiles_pre[4] ~ "Second 25\\%",
                                             accessibility > acc_quantiles_pre[4] ~ "Top 25\\%"),
         accessibility_pre_level = factor(accessibility_pre_level,
                                          levels = c("Top 25\\%", "Second 25\\%", "Third 25\\%", "Bottom 25\\%"),
                                          ordered = TRUE),
         accessibility_during_level = case_when(accessibility <= acc_quantiles_during[2] ~ "Bottom 25\\%",
                                                accessibility > acc_quantiles_during[2] & accessibility <= acc_quantiles_during[3] ~ "Third 25\\%",
                                                accessibility > acc_quantiles_during[3] & accessibility <= acc_quantiles_during[4] ~ "Second 25\\%",
                                                accessibility > acc_quantiles_during[4] ~ "Top 25\\%"),
         accessibility_during_level = factor(accessibility_during_level,
                                             levels = c("Top 25\\%", "Second 25\\%", "Third 25\\%", "Bottom 25\\%"),
                                             ordered = TRUE))
```

```{r aggregate-accessibility-by-age-group, include=FALSE}
summary_pre <- accessibility %>%
  filter(timing == "Pre-covid") %>%
  group_by(accessibility_pre_level) %>%
  summarize(children_pre = sum(children) %>% 
              round(),
            adults_pre = sum(adults) %>% 
              round(),
            seniors_pre = sum(seniors) %>% 
              round(),
            .groups = "drop")

pre_total <- accessibility %>%
  filter(timing == "Pre-covid") %>%
  group_by(timing) %>%
  summarize(children_pre = sum(children) %>% 
              round(),
            adults_pre = sum(adults) %>% 
              round(),
            seniors_pre = sum(seniors) %>% 
              round(),
            .groups = "drop") %>%
  rename(accessibility_pre_level = timing) %>%
  mutate(accessibility_pre_level = "Total population")

summary_pre <- rbind(summary_pre, pre_total)

summary_during <- accessibility %>%
  filter(timing == "During covid") %>%
  group_by(accessibility_during_level) %>%
  summarize(children_during = sum(children) %>% 
              round(),
            adults_during = sum(adults) %>% 
              round(),
            seniors_during = sum(seniors) %>% 
              round(),
            .groups = "drop")

during_total <- accessibility %>%
  filter(timing == "During covid") %>%
  group_by(timing) %>%
  summarize(children_during = sum(children) %>% 
              round(),
            adults_during = sum(adults) %>% 
              round(),
            seniors_during = sum(seniors) %>% 
              round(),
            .groups = "drop") %>%
  rename(accessibility_during_level = timing) %>%
  mutate(accessibility_during_level = "Total population")

summary_during <- rbind(summary_during, during_total)

accessibility_by_age <- cbind(summary_pre, summary_during[,2:4]) 

accessibility_by_age <- accessibility_by_age %>%  
  mutate(children_change = round((children_during - children_pre)/children_pre * 100, 2),
         adults_change = round((adults_during - adults_pre)/adults_pre * 100, 2),
         seniors_change = round((seniors_during - seniors_pre)/seniors_pre * 100, 2),
         children_pre = prettyNum(children_pre, big.mark = ","),
         adults_pre = prettyNum(adults_pre, big.mark = ","),
         seniors_pre = prettyNum(seniors_pre, big.mark = ","),
         children_during = paste0(prettyNum(children_during, big.mark = ","), " (", children_change, "\\%)"),
         adults_during = paste0(prettyNum(adults_during, big.mark = ","), " (", adults_change, "\\%)"),
         seniors_during = paste0(prettyNum(seniors_during, big.mark = ","), " (", seniors_change, "\\%)")) %>%
  transmute(accessibility_pre_level,
            children_pre,
            adults_pre,
            seniors_pre,
            children_during,
            adults_during,
            seniors_during)
```

```{r table-accessibility-by-age-group, echo=FALSE, results='asis'}
accessibility_by_age %>%
  kable("latex",
        booktabs = TRUE,
        align = ("lcccccc"),
        col.names = c("Accessibility Quartile",
                      "Children (age $\\le$ 18)", 
                      "Adults (19-64)", 
                      "Seniors (age $\\ge$ 65)", 
                      "Children (age $\\le$ 18)", 
                      "Adults (19-64)", 
                      "Seniors (age $\\ge$ 65)"),
        caption = "\\label{tab:accessibility-by-age}Population at each accessibility level by age group among members households with incomes less than CAD40,000.",
        escape = FALSE) %>%
  kable_styling(latex_options = c("striped", "scale_down", "hold_position")) %>%
  add_header_above(c(" " = 1, "Pre-COVID-19" = 3, "During COVID-19" = 3)) %>%
  row_spec(4, hline_after = TRUE) %>%
  footnote(general = c("Population values have been rounded.", 
                       "The values in brackets for population during COVID-19 are the changes from before the pandemic."))
```
